SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `artist` (`ArtistId`, `Name`, `EMail`, `CategoryId`, `CountryCode`, `Picture`, `PromoVideo`) VALUES
(1, 'Dead Island', 'untitled-no1@mail.com', 'M', 'AT', '/images/prev/51zRy4inZnL.jpg', 'https://www.youtube.com/watch?v=gETEAHwE2d4'),
(2, '.38 Special', 'di@tasopjis.edu', 'A', 'AT', '/images/prev/415ZSS2GB8L.jpg', 'https://www.youtube.com/watch?v=av7IwBfF5m8'),
(3, '10cc', 'mof@puvoziwo.net', 'A', 'DE', '/images/prev/3454ff43.jpg', 'https://www.youtube.com/watch?v=7InRmTGU0Hg'),
(4, '3 Doors Down', 'ohucep@lugoj.org', 'A', 'US', '/images/prev/25873.jpg', 'https://www.youtube.com/watch?v=eoNAQAP4rZw'),
(5, '4 Non Blondes', 'hucse@vagi.edu', 'A', 'HR', '/images/prev/34343tgr34.jpg', 'https://www.youtube.com/watch?v=E8QejA6xUzo'),
(6, 'a-ha', 'je@ojaridag.org', 'A', 'RO', '/images/prev/141739-tap-106838.jpg', 'https://www.youtube.com/watch?v=t7tA3NNKF0Q'),
(7, 'AC/DC', 'dakag@eje.com', 'M', 'AT', '/images/prev/A-ha-tutupash.jpg', 'https://www.youtube.com/watch?v=9T7NOy8E9g8'),
(8, 'Ace', 'coel@voti.org', 'T', 'AT', '/images/prev/MI0000324965.jpg', 'https://www.youtube.com/watch?v=UE5IW1nDCWw'),
(9, 'Adelitas Way', 'ed@fiifeisi.gov', 'T', 'AT', NULL, 'https://www.youtube.com/watch?v=TWKU2XhY8TA'),
(10, 'Aerosmith', 'felga@lomhagha.io', 'T', 'AT', NULL, 'https://www.youtube.com/watch?v=M9MpSxHxdYM'),
(11, 'Alanis Morissette', 'opibu@kilfawu.gov', 'T', 'AT', NULL, 'https://www.youtube.com/watch?v=XYkhnegFAUc'),
(12, 'Alannah Myles', 'ha@ivohiv.gov', 'T', 'AT', NULL, 'https://www.youtube.com/watch?v=PCeQrYvagGw'),
(13, 'Aldo Nova', 'neroji@sad.org', 'T', 'AT', NULL, 'https://www.youtube.com/watch?v=N3JCjR5cpbA'),
(14, 'Alice Cooper', 'fekneve@sutis.edu', 'T', 'AT', NULL, 'https://www.youtube.com/watch?v=Wvrzyqs62qA'),
(15, 'Alice In Chains', 'jeveslup@vopdiatu.co.uk', 'T', 'AT', NULL, 'https://www.youtube.com/watch?v=OZ50zBaFwlY'),
(16, 'Allman Brothers Band', 'ra@wezagu.io', 'T', 'AT', NULL, 'https://www.youtube.com/watch?v=Ao2A15T8jKo'),
(17, 'America', 'vahed@fitmodsu.co.uk', 'T', 'AT', NULL, NULL),
(18, 'Animals II', 'nited@vavo.co.uk', 'T', 'AT', NULL, NULL),
(19, 'Ann Wilson', 'zi@cozke.gov', 'T', 'UK', NULL, NULL),
(20, 'April Wine', 'wasnuru@dafog.edu', 'A', 'UK', NULL, NULL),
(21, 'Argent', 'wejdekda@juih.net', 'A', 'UK', NULL, NULL),
(22, 'Arlo Guthrie', 'me@fe.com', 'A', 'UK', NULL, NULL),
(23, 'Artful Dodger', 'durgev@le.edu', 'A', 'UK', NULL, NULL),
(24, 'Asia', 'um@genaf.net', 'A', 'UK', NULL, NULL),
(25, 'Atlanta Rhythm Section', 'dufollus@kubnug.io', 'A', 'UK', NULL, NULL),
(26, 'Audioslave', 'hot@atauc.co.uk', 'A', 'UK', NULL, NULL),
(27, 'Autograph', 'todevcu@ceruf.com', 'A', 'UK', NULL, NULL),
(28, 'Axe', 'ane@lod.gov', 'A', 'UK', NULL, NULL),
(29, 'Bachman-Turner Overdrive', 'les@ekcon.net', 'A', 'UK', NULL, NULL),
(30, 'Bad Company', 'uwu@lekbehca.gov', 'A', 'UK', NULL, NULL),
(31, 'Bad English', 'tuijzi@ho.net', 'A', 'UK', NULL, NULL),
(32, 'Badfinger', 'adotuku@gib.com', 'A', 'UK', NULL, NULL),
(33, 'Baton Rouge', 'jusomfos@jimudwu.edu', 'A', 'UK', NULL, NULL),
(34, 'Beastie Boys', 'nudmupam@kepojof.gov', 'A', 'UK', NULL, NULL),
(35, 'Beck', 'lucfin@suapogem.edu', 'A', 'UK', NULL, NULL),
(36, 'Big Country', 'akoenusa@has.net', 'A', 'BR', NULL, NULL),
(37, 'Bill Haley', 'zeuze@cu.io', 'A', 'BR', NULL, NULL),
(38, 'Bill Withers', 'agiodolu@latzoha.net', 'A', 'BR', NULL, NULL),
(39, 'Billy Idol', 'nal@hulug.com', 'A', 'BR', NULL, NULL),
(40, 'Billy Joel', 'ub@mesuril.org', 'A', 'BR', NULL, NULL),
(41, 'Billy Rankin', 'nuze@mawwup.com', 'A', 'BR', NULL, NULL),
(42, 'Billy Squier', 'ruzoga@umeaha.io', 'A', 'BR', NULL, NULL),
(43, 'Billy Thorpe', 'imihetpeg@boc.org', 'C', 'BR', NULL, NULL),
(44, 'Black Sabbath', 'ela@lodu.io', 'C', 'BR', NULL, NULL),
(45, 'Blackfoot', 'koemuifo@anakuhmes.org', 'C', 'BR', NULL, NULL),
(46, 'Blind Faith', 'ro@jate.org', 'C', 'BR', NULL, NULL),
(47, 'Blind Melon', 'kovepte@bidde.io', 'C', 'BR', NULL, NULL),
(48, 'Blink-182', 'vilajed@sazgi.io', 'C', 'AR', NULL, NULL),
(49, 'Blondie', 'bu@ewdal.org', 'C', 'AR', NULL, NULL),
(50, 'Blue Oyster Cult', 'ti@defce.org', 'C', 'AR', NULL, NULL),
(51, 'Blur', 'habjiz@gasod.com', 'C', 'AR', NULL, NULL),
(52, 'Bob Dylan', 'ba@ga.io', 'C', 'AR', NULL, NULL),
(53, 'Bob Marley', 'wicowe@vi.edu', 'C', 'AR', NULL, NULL),
(54, 'Bob Seger', 'zeczug@pawek.net', 'C', 'AR', NULL, NULL),
(55, 'Bob Welch', 'opzor@ginsaf.io', 'C', 'AR', NULL, NULL),
(56, 'Bon Jovi', 'os@sulakut.co.uk', 'C', 'AR', NULL, NULL),
(57, 'Bonham', 'oneta@zisomgem.co.uk', 'C', 'AR', NULL, NULL),
(58, 'Booker T. and the MGs', 'dormacvo@pi.com', 'C', 'AR', NULL, NULL),
(59, 'Boston', 'wacolu@cahju.net', 'C', 'AR', NULL, NULL),
(60, 'Boz Scaggs', 'voz@haaf.com', 'C', 'AR', NULL, NULL),
(61, 'Brewer & Shipley', 'futji@fuwfoiwe.gov', 'C', 'AR', NULL, NULL),
(62, 'Bruce Hornsby & The Range', 'ze@zoblama.com', 'A', 'AR', NULL, NULL),
(63, 'Bruce Springsteen', 'bu@wo.edu', 'A', 'AR', NULL, NULL),
(64, 'Bryan Adams', 'wowulipe@ervap.edu', 'A', 'AR', NULL, NULL),
(65, 'Buckcherry', 'pajupgi@oti.net', 'A', 'AR', NULL, NULL),
(66, 'Buffalo Springfield', 'jom@izawimam.co.uk', 'A', 'AR', NULL, NULL),
(67, 'Bush', 'ac@erbetifa.edu', 'A', 'AR', NULL, NULL),
(68, 'Candlebox', 'ewauhuag@vodew.gov', 'A', 'AR', NULL, NULL),
(69, 'Canned Heat', 'tu@mip.org', 'A', 'AR', NULL, NULL),
(70, 'Carole King', 'jufijuv@porvu.io', 'C', 'BG', NULL, NULL),
(71, 'Cat Stevens', 'umogawuf@fot.net', 'C', 'BO', NULL, NULL),
(72, 'Charlie Daniels Band', 'fumcohbe@ja.org', 'C', 'BG', NULL, NULL),
(73, 'Cheap Trick', 'didazato@camhi.gov', 'C', 'BO', NULL, NULL),
(74, 'Chevelle', 'fen@humu.net', 'C', 'BG', NULL, NULL),
(75, 'Chicago', 'huw@vilansuh.co.uk', 'C', 'BO', NULL, NULL),
(76, 'Chuck Berry', 'piccaj@uhi.co.uk', 'C', 'BG', NULL, NULL),
(77, 'Cinderella', 'lofim@hiis.gov', 'C', 'BO', NULL, NULL),
(78, 'Clarks', 'fofisur@hav.com', 'C', 'BG', NULL, NULL),
(79, 'Collective Soul', 'likmekuj@beim.gov', 'C', 'BO', NULL, NULL),
(80, 'Commander Cody', 'zogfe@lipgim.io', 'C', 'BG', NULL, NULL),
(81, 'Coney Hatch', 'benbo@ozokoz.gov', 'C', 'BO', NULL, NULL),
(82, 'Counting Crows', 'carwiw@te.gov', 'C', 'BG', NULL, NULL),
(83, 'Cracker', 'gusoc@muj.edu', 'C', 'BO', NULL, NULL),
(84, 'Cream', 'hujemo@bibegje.org', 'C', 'BG', NULL, NULL),
(85, 'Creed', 'riniked@ke.com', 'C', 'BO', NULL, NULL),
(86, 'Creedence Clearwater Revival', 'ufonirrat@izwer.net', 'C', 'BG', NULL, NULL),
(87, 'Crosby, Stills & Nash', 'suckuiko@fe.co.uk', 'C', 'BO', NULL, NULL),
(88, 'Crosby, Stills, Nash & Young', 'acojef@ro.edu', 'C', 'BG', NULL, NULL),
(89, 'Cutting Crew', 'mi@sa.co.uk', 'C', 'BO', NULL, NULL),
(90, 'Damn Yankees', 'mif@avcele.edu', 'C', 'BG', NULL, NULL),
(91, 'Dave Edmunds', 'vewah@ne.edu', 'C', 'BO', NULL, NULL),
(92, 'Dave Mason', 'mijiehi@eb.co.uk', 'C', 'BG', NULL, NULL),
(93, 'David & David', 'buada@am.edu', 'C', 'BO', NULL, NULL),
(94, 'David Bowie', 'jat@mibab.net', 'C', 'BG', NULL, NULL),
(95, 'David Essex', 'umumarpu@hosih.org', 'C', 'GA', NULL, NULL),
(96, 'David Gilmour', 'itawephe@ah.net', 'C', 'GB', NULL, NULL),
(97, 'David Johansen', 'fekbiiha@gugkehruv.net', 'C', 'GD', NULL, NULL),
(98, 'David Lee Roth', 'tiupo@diwobet.com', 'C', 'GE', NULL, NULL),
(99, 'Deep Purple', 'funzuccu@vejgulo.edu', 'C', 'GF', NULL, NULL),
(100, 'Def Leppard', 'gokez@ekepameb.net', 'C', 'GG', NULL, NULL),
(101, 'Depeche Mode', 'ato@owite.com', 'C', 'GH', NULL, NULL),
(102, 'Derek & The Dominos', 'wa@nitu.edu', 'C', 'GI', NULL, NULL),
(103, 'Detective', 'jikzol@tac.gov', 'C', 'GL', NULL, NULL),
(104, 'Dick Siegel', 'circildum@popbeki.edu', 'C', 'GM', NULL, NULL),
(105, 'Dio', 'konecu@fow.com', 'C', 'GN', NULL, NULL),
(106, 'Dire Straits', 'ikdihsik@tocippaf.edu', 'C', 'GP', NULL, NULL),
(107, 'Dishwalla', 'va@vinlilfo.org', 'C', 'GQ', NULL, NULL),
(108, 'Dobie Gray', 'jozhabci@virar.io', 'C', 'GR', NULL, NULL),
(109, 'Dokken', 'cewhehki@ho.com', 'C', 'GT', NULL, NULL),
(110, 'Don Felder', 'bogo@afjevak.com', 'C', 'GU', NULL, NULL),
(111, 'Don Henley', 'huel@furca.com', 'C', 'GY', NULL, NULL),
(112, 'Don McLean', 'repokla@funpe.net', 'C', 'HK', NULL, NULL),
(113, 'Donnie Iris', 'dotubmeg@vopi.edu', 'C', 'HN', NULL, NULL),
(114, 'Donovan', 'eno@hajermu.edu', 'C', 'HR', NULL, NULL),
(115, 'Dr. Hook & the Medicine Show', 'cowhoban@gedovik.co.uk', 'C', 'HT', NULL, NULL),
(116, 'Dr. John', 'cektemof@wuchepuz.edu', 'C', 'HU', NULL, NULL),
(117, 'Dramarama', 'jouwjof@fozfulhe.io', 'C', 'ID', NULL, NULL),
(118, 'Led Zeppelin', 'cekzici@faeguda.net', 'C', 'IE', NULL, NULL),
(119, 'Duran Duran', 'bubgu@berfu.co.uk', 'C', 'IL', NULL, NULL),
(120, 'Eagles', 'ifocilho@kuttucsel.io', 'C', 'IM', NULL, NULL),
(121, 'Eddie Money', 'vavwema@dad.edu', 'C', 'IN', NULL, NULL),
(122, 'Edgar Winter Group', 'zo@hu.gov', 'C', 'IO', NULL, NULL),
(123, 'Edwin Starr', 'anvatuk@cufo.org', 'C', 'IQ', NULL, NULL),
(124, 'Electric Light Orchestra', 'iga@raf.io', 'C', 'IR', NULL, NULL),
(125, 'Elton John', 'lagguro@po.com', 'C', 'IS', NULL, NULL),
(126, 'Elvin Bishop', 'no@ni.co.uk', 'C', 'IT', NULL, NULL),
(127, 'Elvis Costello', 'ke@muba.edu', 'C', 'JE', NULL, NULL),
(128, 'Emerson, Lake & Palmer', 'cumul@pu.org', 'C', 'JM', NULL, NULL),
(129, 'Eric Clapton', 'ubunfuk@ilek.gov', 'C', 'JO', NULL, NULL),
(130, 'Eric Johnson', 'wig@kizjug.gov', 'C', 'JP', NULL, NULL),
(131, 'Europe', 'vezjud@lid.gov', 'C', 'KE', NULL, NULL),
(132, 'Eurythmics', 'mewfaos@di.org', 'C', 'KG', NULL, NULL),
(133, 'Eve 6', 'ruvamo@inzi.com', 'C', 'KH', NULL, NULL),
(134, 'Everclear', 'voboc@ut.co.uk', 'C', 'KI', NULL, NULL),
(135, 'Everlast', 'sijognab@wamefe.com', 'C', 'KM', NULL, NULL),
(136, 'Extreme', 'da@elatid.io', 'C', 'KP', NULL, NULL),
(137, 'Faces', 'do@erivefpuw.com', 'C', 'KR', NULL, NULL),
(138, 'Faith No More', 'av@vazagiko.io', 'C', 'GA', NULL, NULL),
(139, 'Faster Pussycat', 'tiholi@dehho.org', 'C', 'GB', NULL, NULL),
(140, 'Firm', 'teucadaw@kemad.com', 'C', 'GD', NULL, NULL),
(141, 'Five Man Electrical Band', 'hawejze@warocup.gov', 'C', 'GE', NULL, NULL),
(142, 'Fleetwood Mac', 'nemaen@tolabul.co.uk', 'C', 'GF', NULL, NULL),
(143, 'Focus', 'uhjovik@moh.net', 'C', 'GG', NULL, NULL),
(144, 'Foghat', 'daho@wese.com', 'C', 'GH', NULL, NULL),
(145, 'Foo Fighters', 'rizoz@pac.edu', 'C', 'GI', NULL, NULL),
(146, 'Foreigner', 'wowu@eg.gov', 'C', 'GL', NULL, NULL),
(147, 'Frank Zappa', 'weiznu@go.com', 'F', 'GM', NULL, NULL),
(148, 'Free', 'niz@kufavu.io', 'F', 'GN', NULL, NULL),
(149, 'Funkadelic', 'opi@mu.org', 'F', 'GP', NULL, NULL),
(150, 'Gary Numan', 'ub@wat.io', 'F', 'GQ', NULL, NULL),
(151, 'Gary Wright', 'binsu@samo.edu', 'F', 'GR', NULL, NULL),
(152, 'Genesis', 'rocjus@oftehi.net', 'F', 'GT', NULL, NULL),
(153, 'George Harrison', 'towad@naplous.edu', 'F', 'GU', NULL, NULL),
(154, 'George Thorogood', 'robevwu@rem.com', 'F', 'GY', NULL, NULL),
(155, 'Georgia Satellites', 'jewuwet@niihe.org', 'F', 'HK', NULL, NULL),
(156, 'Gerry Rafferty', 'kopuj@nufnijo.edu', 'F', 'HN', NULL, NULL),
(157, 'Gin Blossoms', 'zico@ave.co.uk', 'F', 'HR', NULL, NULL),
(158, 'Glenn Frey', 've@dunvuduz.co.uk', 'F', 'HT', NULL, NULL),
(159, 'Gold Star Ballroom Orchestra', 'ev@jozesepa.org', 'F', 'HU', NULL, NULL),
(160, 'Golden Earring', 'mam@tuoc.gov', 'F', 'ID', NULL, NULL),
(161, 'Gordon Lightfoot', 'akozew@todul.io', 'F', 'IE', NULL, NULL),
(162, 'Gov t Mule', 'var@koka.co.uk', 'F', 'IL', NULL, NULL),
(163, 'Grand Funk Railroad', 'didab@iwa.co.uk', 'F', 'IM', NULL, NULL),
(164, 'Grateful Dead', 'kibiwvi@duomip.io', 'F', 'IN', NULL, NULL),
(165, 'Great White', 'ji@usece.co.uk', 'F', 'IO', NULL, NULL),
(166, 'Green Day', 'cekraf@ma.co.uk', 'F', 'IQ', NULL, NULL),
(167, 'Greg Kihn Band', 'ta@ze.co.uk', 'F', 'IR', NULL, NULL),
(168, 'Gregg Allman', 'geor@vaoli.com', 'F', 'IS', NULL, NULL),
(169, 'Guess Who', 'gob@sab.io', 'F', 'IT', NULL, NULL),
(170, 'Guns N Roses', 'gozuthih@ragbenivi.net', 'F', 'JE', NULL, NULL),
(171, 'Gypsy', 'bosrifjo@leskalab.edu', 'F', 'JM', NULL, NULL),
(172, 'Harold Faltermeyer', 'muav@tahcefguj.edu', 'F', 'JO', NULL, NULL),
(173, 'Harry Chapin', 'iziviti@gujbog.io', 'F', 'JP', NULL, NULL),
(174, 'Harry Nilsson', 'pofiigu@bejehuw.edu', 'F', 'KE', NULL, NULL),
(175, 'Head East', 'tad@cujike.org', 'F', 'KG', NULL, NULL),
(176, 'Heart', 'ruzin@puhave.co.uk', 'F', 'KH', NULL, NULL),
(177, 'Heartsfield', 'tukuwe@pija.net', 'F', 'KI', NULL, NULL),
(178, 'HellYeah', 'bib@hob.edu', 'F', 'KM', NULL, NULL),
(179, 'Henry Paul Band', 'nuutsav@pacekzem.net', 'F', 'KP', NULL, NULL),
(180, 'Hollies', 'ehevaho@vijna.gov', 'F', 'KR', NULL, NULL),
(181, 'Honeymoon Suite', 'gawus@jo.org', 'F', 'KW', NULL, NULL),
(182, 'Hooters', 'gon@dechotok.edu', 'F', 'KY', NULL, NULL),
(183, 'Huey Lewis & The News', 'zo@bot.net', 'F', 'KZ', NULL, NULL),
(184, 'Humble Pie', 'toho@puwmezpu.net', 'F', 'LA', NULL, NULL),
(185, 'Iggy Pop', 'lak@ta.io', 'F', 'LB', NULL, NULL),
(186, 'Imagine Dragons', 'cawuceg@da.org', 'F', 'LC', NULL, NULL),
(187, 'INXS', 'jatu@guto.org', 'F', 'LI', NULL, NULL),
(188, 'Iron Butterfly', 'gougoat@jivo.gov', 'F', 'LK', NULL, NULL),
(189, 'Iron Maiden', 'coz@ov.com', 'F', 'LR', NULL, NULL),
(190, 'J. Geils Band', 'cahjo@ziwwenso.edu', 'F', 'LS', NULL, NULL),
(191, 'Jackson Browne', 'kuk@kenomieno.com', 'J', 'LT', NULL, NULL),
(192, 'James Gang', 'ni@cessogeso.co.uk', 'J', 'LU', NULL, NULL),
(193, 'JAMES TAYLOR', 'pir@tece.org', 'J', 'NZ', NULL, NULL),
(194, 'Jane s Addiction', 'robonir@jub.edu', 'J', 'OM', NULL, NULL),
(195, 'Janis Joplin', 'mosat@esitiva.io', 'J', 'PA', NULL, NULL),
(196, 'Jay Ferguson', 'naoju@bun.edu', 'J', 'PE', NULL, NULL),
(197, 'Jeff Beck', 'bubfobwic@de.com', 'J', 'PF', NULL, NULL),
(198, 'Jefferson Airplane', 'fugotzu@reki.edu', 'J', 'PG', NULL, NULL),
(199, 'Jefferson Starship', 'bokek@gojji.org', 'J', 'PH', NULL, NULL),
(200, 'Jesus Jones', 'kuw@ji.co.uk', 'J', 'PK', NULL, NULL),
(201, 'Jet', 'jik@kurori.org', 'J', 'PL', NULL, NULL),
(202, 'Jethro Tull', 're@jut.co.uk', 'J', 'PN', NULL, NULL),
(203, 'Jim Croce', 'bigzijbo@zodacbo.com', 'J', 'PR', NULL, NULL),
(204, 'Jimi Hendrix', 'wed@puzhujrud.gov', 'J', 'PS', NULL, NULL),
(205, 'Jimmy Buffett', 'mabalu@okaaku.gov', 'L', 'PT', NULL, NULL),
(206, 'Joan Jett', 'waksuko@zuow.co.uk', 'L', 'PW', NULL, NULL),
(207, 'Joe Cocker', 'wo@ot.org', 'L', 'PY', NULL, NULL),
(208, 'Joe Jackson', 'suwu@ezo.net', 'L', 'QA', NULL, NULL),
(209, 'Joe Satriani', 'bif@ta.org', 'L', 'RO', NULL, NULL),
(210, 'Joe Walsh', 'rostuseg@dupset.io', 'L', 'RS', NULL, NULL),
(211, 'John Cafferty', 'igoab@wewa.edu', 'L', 'RU', NULL, NULL),
(212, 'John Fogerty', 'ves@ozi.io', 'M', 'RW', NULL, NULL),
(213, 'John Lennon', 'isu@sakdid.gov', 'M', 'SA', NULL, NULL),
(214, 'John Mellencamp', 'utugciw@op.org', 'M', 'SB', NULL, NULL),
(215, 'John Prine', 'es@bekicnag.io', 'M', 'SC', NULL, NULL),
(216, 'Johnny Nash', 'ugvam@muzicatoz.edu', 'M', 'SD', NULL, NULL),
(217, 'Johnny Van Zant', 'iczeb@dehe.io', 'M', 'SE', NULL, NULL),
(218, 'Jonathan Edwards', 'wotuc@kansukil.gov', 'M', 'SG', NULL, NULL),
(219, 'Jonathan Richman', 'bemaoh@ovdieri.co.uk', 'M', 'SH', NULL, NULL),
(220, 'Journey', 'cot@betoiw.edu', 'M', 'SI', NULL, NULL),
(221, 'Judas Priest', 'lessefis@wioc.edu', 'M', 'SK', NULL, NULL),
(222, 'Junkyard', 'wo@ap.edu', 'M', 'NZ', NULL, NULL),
(223, 'Kansas', 'ka@vodob.com', 'M', 'OM', NULL, NULL),
(224, 'Kenny Loggins', 'dic@poda.io', 'M', 'PA', NULL, NULL),
(225, 'Kenny Wayne Shepherd', 'huofdoc@hasel.com', 'M', 'PE', NULL, NULL),
(226, 'Kid Rock', 'fo@zabalup.net', 'M', 'PF', NULL, NULL),
(227, 'Kingofthehill', 'kulasenud@anjame.net', 'M', 'PG', NULL, NULL),
(228, 'Kings of Leon', 'nevocub@go.edu', 'M', 'PH', NULL, NULL),
(229, 'Kiss', 'za@cuwahpo.com', 'M', 'PK', NULL, NULL),
(230, 'Krokus', 'ro@abzuz.net', 'M', 'PL', NULL, NULL),
(231, 'L.A. Guns', 'misi@bibaj.io', 'J', 'PN', NULL, NULL),
(232, 'Lake', 'wa@kolzejow.io', 'J', 'PR', NULL, NULL),
(233, 'Lee Michaels', 'uhsiwa@dari.co.uk', 'J', 'PS', NULL, NULL),
(234, 'Legs Diamond', 'reze@unhodga.io', 'J', 'PT', NULL, NULL),
(235, 'Lenny Kravitz', 'liw@wuiv.org', 'J', 'PW', NULL, NULL),
(236, 'Leon Russell', 'ivouzec@eda.com', 'J', 'PY', NULL, NULL),
(237, 'Lit', 'bugjimbuh@et.gov', 'J', 'QA', NULL, NULL),
(238, 'Lita Ford', 'rod@nufes.io', 'J', 'RO', NULL, NULL),
(239, 'Little Feat', 'mu@duata.com', 'J', 'RS', NULL, NULL),
(240, 'Live', 'dib@wotazgo.net', 'J', 'RU', NULL, NULL),
(241, 'Living Colour', 'cudauru@puf.com', 'J', 'RW', NULL, NULL),
(242, 'Local H', 'idtek@pif.co.uk', 'J', 'SA', NULL, NULL),
(243, 'London Symphony Orchestra', 'eguri@iwgi.gov', 'J', 'SB', NULL, NULL),
(244, 'Lou Gramm', 'ho@pahu.org', 'J', 'SC', NULL, NULL),
(245, 'Lou Reed', 'mubo@isomomeh.org', 'J', 'SL', NULL, NULL),
(246, 'Loverboy', 'ati@vicsa.co.uk', 'J', 'SM', NULL, NULL),
(247, 'Lynch Mob', 'uwe@lal.co.uk', 'M', 'SN', NULL, NULL),
(248, 'Lynyrd Skynyrd', 'uluretoj@jav.org', 'M', 'SO', NULL, NULL),
(249, 'Mama s Pride', 'nu@ivvuos.com', 'M', 'SR', NULL, NULL),
(250, 'Manfred Mann', 'so@hu.net', 'M', 'SS', NULL, NULL),
(251, 'Marcy Playground', 'verifwi@cibuezo.net', 'M', 'SV', NULL, NULL),
(252, 'Meat Loaf', 'hi@ges.edu', 'M', 'SX', NULL, NULL),
(253, 'Melissa Etheridge', 'durso@gimivda.org', 'M', 'SY', NULL, NULL),
(254, 'Men At Work', 'civieki@sa.io', 'M', 'SZ', NULL, NULL),
(255, 'Metallica', 'bejer@awu.edu', 'M', 'TD', NULL, NULL),
(256, 'Michael Nesmith', 'gupu@votilru.com', 'M', 'TG', NULL, NULL),
(257, 'Michael Stanley', 'jin@umi.edu', 'M', 'TH', NULL, NULL),
(258, 'Midnight Oil', 'aweefima@sog.edu', 'M', 'TJ', NULL, NULL),
(259, 'Mitch Ryder', 'ellilo@sozeare.edu', 'M', 'TK', NULL, NULL),
(260, 'Modern English', 'ijainaben@behwa.com', 'M', 'TL', NULL, NULL),
(261, 'Molkie Cole', 'notinoho@odudetul.co.uk', 'M', 'TM', NULL, NULL),
(262, 'Molly Hatchet', 'wavzamfet@luipe.co.uk', 'M', 'TN', NULL, NULL),
(263, 'Monroes', 'ku@lensam.com', 'M', 'TO', NULL, NULL),
(264, 'Montrose', 'ufnazhom@roesdi.io', 'M', 'TR', NULL, NULL),
(265, 'Motley Crue', 'bugzupsew@bodpa.net', 'M', 'TT', NULL, NULL),
(266, 'Mott the Hoople', 'musove@bin.gov', 'M', 'TV', NULL, NULL),
(267, 'Mountain', 'lu@oruzu.org', 'M', 'TW', NULL, NULL),
(268, 'Moxy', 'rupfek@nincojo.co.uk', 'M', 'TZ', NULL, NULL),
(269, 'Mr. Big', 'ejo@godbafbag.edu', 'M', 'UA', NULL, NULL),
(270, 'Mungo Jerry', 'ki@ho.io', 'M', 'UG', NULL, NULL),
(271, 'Nazareth', 'deroli@zisheba.gov', 'M', 'US', NULL, NULL),
(272, 'Neil Young', 'mer@ondah.co.uk', 'M', 'UY', NULL, NULL),
(273, 'Nektar', 'sihiuv@hup.edu', 'M', 'UZ', NULL, NULL),
(274, 'Nickelback', 'pogpijruj@ne.net', 'M', 'VA', NULL, NULL),
(275, 'Night Ranger', 'sev@fohna.org', 'M', 'VE', NULL, NULL),
(276, 'Nirvana', 'susrec@telju.co.uk', 'M', 'SL', NULL, NULL),
(277, 'Norman Greenbaum', 'huegluf@ofwegu.io', 'M', 'SM', NULL, NULL),
(278, 'Nothing More', 'emo@curhozviw.edu', 'M', 'SN', NULL, NULL),
(279, 'Oasis', 'zumihak@dare.io', 'M', 'SO', NULL, NULL),
(280, 'Orleans', 'zuzcosroj@izovoj.net', 'M', 'SR', NULL, NULL),
(281, 'Otis Redding', 'roso@habawfav.co.uk', 'M', 'SS', NULL, NULL),
(282, 'Ozark Mountain Daredevils', 'vitcek@dimocwa.org', 'M', 'SV', NULL, NULL),
(283, 'Ozzy Osbourne', 'kohemic@ah.io', 'M', 'SX', NULL, NULL),
(284, 'Pat Benatar', 'muduvom@ecfis.com', 'M', 'SY', NULL, NULL),
(285, 'Pat Travers', 'wovfujim@puohi.io', 'M', 'SZ', NULL, NULL),
(286, 'Paul McCartney & Linda McCartn', 'gigpegguf@wiwa.net', 'M', 'TD', NULL, NULL),
(287, 'Paul McCartney & Wings', 'zicmivec@gutoc.com', 'M', 'TG', NULL, NULL),
(288, 'Paul Simon', 'kuw@som.com', 'M', 'TH', NULL, NULL),
(289, 'Pearl Jam', 'su@pi.co.uk', 'M', 'TJ', NULL, NULL),
(290, 'Pete Townshend', 'jalu@fori.edu', 'M', 'TK', NULL, NULL),
(291, 'Peter Frampton', 'eluja@imrovpo.net', 'M', 'TL', NULL, NULL),
(292, 'Peter Gabriel', 'purwo@ju.org', 'M', 'TM', NULL, NULL),
(293, 'Phil Collins', 'golo@ewjanpow.edu', 'M', 'TN', NULL, NULL),
(294, 'Pink Floyd', 'idezak@ido.gov', 'M', 'TO', NULL, NULL),
(295, 'Poison', 'wo@hamafeb.com', 'M', 'TR', NULL, NULL),
(296, 'Procol Harum', 'pifvudtob@tasve.io', 'M', 'TT', NULL, NULL),
(297, 'Puddle of Mudd', 'vezikajep@uh.org', 'M', 'TV', NULL, NULL),
(298, 'Pure Prairie League', 'nakewok@focbaanu.edu', 'M', 'TW', NULL, NULL),
(299, 'Queen', 'gecar@medu.net', 'M', 'TZ', NULL, NULL),
(300, 'Queen / David Bowie', 'afo@feofijar.net', 'M', 'UA', NULL, NULL),
(301, 'Queens of the Stone Age', 'egpeve@mukhep.edu', 'M', 'UG', NULL, NULL),
(302, 'Queensryche', 'hi@lehip.edu', 'M', 'US', NULL, NULL),
(303, 'Quicksilver Messenger Service', 'ja@jocani.io', 'M', 'UY', NULL, NULL),
(304, 'Quiet Riot', 'ersis@hik.co.uk', 'M', 'UZ', NULL, NULL),
(305, 'R.E.M.', 'mubidanom@leiv.com', 'M', 'VA', NULL, NULL),
(306, 'Rainbow', 'ezogi@sadjaceb.gov', 'M', 'VE', NULL, NULL),
(307, 'Ram Jam', 'harmet@mehpu.edu', 'M', 'VN', NULL, NULL),
(308, 'Ratt', 'libopta@gu.org', 'M', 'VU', NULL, NULL),
(309, 'Red Hot Chili Peppers', 'suc@bebkereno.org', 'M', 'WF', NULL, NULL),
(310, 'Red Rider', 'zuw@mad.gov', 'M', 'WS', NULL, NULL),
(311, 'REO Speedwagon', 'jadce@babzoz.com', 'M', 'XK', NULL, NULL),
(312, 'Rick Derringer', 'bo@huare.edu', 'M', 'TZ', NULL, NULL),
(313, 'Rick Springfield', 'nag@aluewe.gov', 'M', 'UA', NULL, NULL),
(314, 'Ringo Starr', 'tet@uvugul.com', 'M', 'UG', NULL, NULL),
(315, 'Robert Palmer', 'ileje@itbog.co.uk', 'M', 'US', NULL, NULL),
(316, 'Robert Plant', 'tes@lepocebo.io', 'M', 'UY', NULL, NULL),
(317, 'Robert Tepper', 'lupu@vuzennek.gov', 'M', 'UZ', NULL, NULL),
(318, 'Robin Trower', 'kusvuwur@vutofzuv.io', 'M', 'VA', NULL, NULL),
(319, 'Rockets', 'mujak@jowigiho.net', 'M', 'VE', NULL, NULL),
(320, 'Rocky Burnette', 'putka@ajwocow.com', 'M', 'VN', NULL, NULL),
(321, 'Rod Stewart', 'jotwunguw@dakew.gov', 'M', 'VU', NULL, NULL),
(322, 'Roger Daltry', 'favfuh@li.net', 'M', 'WF', NULL, NULL),
(323, 'Roger Hodgson', 'egudujop@loude.net', 'M', 'WS', NULL, NULL),
(324, 'Rolling Stones', 'kucjonjo@san.io', 'M', 'XK', NULL, NULL),
(325, 'Rory Gallagher', 'totpu@hioja.co.uk', 'M', 'US', NULL, NULL),
(326, 'Royal Bliss', 'ampu@jizsuj.com', 'M', 'US', NULL, NULL),
(327, 'Rush', 'focrobke@kugab.io', 'M', 'US', NULL, NULL),
(328, 'Russ Ballard', 'ra@iza.edu', 'M', 'US', NULL, NULL),
(329, 'Saga', 'zaciguej@cenco.edu', 'M', 'US', NULL, NULL),
(330, 'Sam & Dave', 'rohuhji@ji.net', 'M', 'US', NULL, NULL),
(331, 'Sammy Hagar', 'pom@ikide.com', 'M', 'US', NULL, NULL),
(332, 'Santana', 'cow@vuhrojal.com', 'M', 'US', NULL, NULL),
(333, 'Scandal', 'nepnif@apvudbav.net', 'OT', 'US', NULL, NULL),
(334, 'School Of Fish', 'paf@rifoaju.edu', 'OT', 'US', NULL, NULL),
(335, 'Scorpions', 'uwcij@viepesur.com', 'OT', 'US', NULL, NULL),
(336, 'Seether', 'gado@ot.edu', 'OT', 'US', NULL, NULL),
(337, 'Sex Pistols', 'wudcokro@vefotro.com', 'OT', 'US', NULL, NULL),
(338, 'Sherbs', 'selek@biho.org', 'OT', 'US', NULL, NULL),
(339, 'Shinedown', 'kebef@nijafusoh.edu', 'OT', 'US', NULL, NULL),
(340, 'Simon & Garfunkel', 'sansac@haro.edu', 'OT', 'US', NULL, NULL),
(341, 'Simple Minds', 'ed@soiwi.com', 'OT', 'US', NULL, NULL),
(342, 'Skid Row', 'cegso@taokrek.gov', 'OT', 'US', NULL, NULL),
(343, 'Slaughter', 'mizu@gus.com', 'OT', 'US', NULL, NULL),
(344, 'Smash Mouth', 'etfi@ildisa.net', 'OT', 'US', NULL, NULL),
(345, 'Smashing Pumpkins', 'huluwel@jebecih.io', 'OT', 'US', NULL, NULL),
(346, 'Sniff n the Tears', 'agiz@zubvusuk.com', 'OT', 'US', NULL, NULL),
(347, 'Soft Cell', 'pup@bazbi.com', 'OT', 'DE', NULL, NULL),
(348, 'Soundgarden', 'zec@lisa.edu', 'OT', 'DE', NULL, NULL),
(349, 'Southside Johnny', 'busru@borivu.gov', 'OT', 'DE', NULL, NULL),
(350, 'Spencer Davis Group', 'pozvej@ec.edu', 'OT', 'DE', NULL, NULL),
(351, 'Spin Doctors', 'juleluhu@ahbu.edu', 'OT', 'DE', NULL, NULL),
(352, 'Squeeze', 'zu@fetfomvum.com', 'OT', 'DE', NULL, NULL),
(353, 'Staind', 'vit@hilnipsos.gov', 'OT', 'DE', NULL, NULL),
(354, 'Starset', 'udi@zeca.io', 'OT', 'DE', NULL, NULL),
(355, 'Stealers Wheel', 'pu@fodogalif.net', 'OT', 'DE', NULL, NULL),
(356, 'Steely Dan', 'rak@zezmazan.com', 'S', 'DE', NULL, NULL),
(357, 'Stephen Stills', 'socsaj@azlumes.com', 'S', 'DE', NULL, NULL),
(358, 'Steppenwolf', 'geped@pujrafko.com', 'S', 'DE', NULL, NULL),
(359, 'Steve Earle', 'pafiur@duhu.gov', 'S', 'DE', NULL, NULL),
(360, 'Steve Miller Band', 'seez@fecibwuw.co.uk', 'S', 'DE', NULL, NULL),
(361, 'Steve Perry', 'zemjek@gijuc.io', 'S', 'DE', NULL, NULL),
(362, 'Steve Winwood', 'luha@kic.edu', 'S', 'DE', NULL, NULL),
(363, 'Steven Stills', 'mob@rossim.org', 'S', 'DE', NULL, NULL),
(364, 'Stevie Nicks', 'okeso@fuhcob.co.uk', 'S', 'DE', NULL, NULL),
(365, 'Stevie Nicks Tom Petty and the', 'tubejhe@ho.edu', 'S', 'DE', NULL, NULL),
(366, 'Stevie Ray Vaughan', 'ofo@ce.net', 'S', 'DE', NULL, NULL),
(367, 'Stevie Wonder', 'vir@fourawaz.io', 'S', 'DE', NULL, NULL),
(368, 'Sting', 'bun@ro.co.uk', 'St', 'DE', NULL, NULL),
(369, 'Stone Temple Pilots', 'isogo@fapa.net', 'St', 'DE', NULL, NULL),
(370, 'Stray Cats', 'tafhuvuf@ziocla.com', 'St', 'DE', NULL, NULL),
(371, 'Stryper', 'raddos@vuw.net', 'St', 'DE', NULL, NULL),
(372, 'Stu Nunnery', 'bilab@adajapgim.co.uk', 'St', 'AT', NULL, NULL),
(373, 'Styx', 'wul@gog.edu', 'St', 'AT', NULL, NULL),
(374, 'Sublime', 'zi@gauhi.net', 'St', 'AT', NULL, NULL),
(375, 'Sugar Ray', 'mav@avni.net', 'St', 'AT', NULL, NULL),
(376, 'Sugarloaf', 'vebvu@sa.co.uk', 'St', 'AT', NULL, NULL),
(377, 'Supertramp', 'dew@wup.net', 'St', 'AT', NULL, NULL),
(378, 'Survivor', 'kas@kes.net', 'St', 'AT', NULL, NULL),
(379, 'Sweet', 'meut@ugewe.co.uk', 'St', 'AT', NULL, NULL),
(380, 'T. Rex', 'owwusja@bazsig.org', 'St', 'AT', NULL, NULL),
(381, 'Talking Heads', 'vom@habopam.edu', 'St', 'AT', NULL, NULL),
(382, 'Taxxi', 'vachuv@pudbordu.net', 'St', 'AT', NULL, NULL),
(383, 'Tears for Fears', 'ew@dookojor.com', 'St', 'AT', NULL, NULL),
(384, 'Ted Nugent', 'ruw@ad.co.uk', 'St', 'AT', NULL, NULL),
(385, 'Temple of the Dog', 'oj@ol.org', 'St', 'AT', NULL, NULL),
(386, 'Ten Years After', 'tokuvo@gara.co.uk', 'S', 'AT', NULL, NULL),
(387, 'Tesla', 'eviehedor@fuofne.io', 'S', 'AT', NULL, NULL),
(388, 'The Alan Parsons Project', 'ut@wo.edu', 'S', 'AT', NULL, NULL),
(389, 'The Alarm (IRS)', 'bajdo@elohiri.com', 'S', 'AT', NULL, NULL),
(390, 'The Amboy Dukes', 'zidojbem@eraku.gov', 'S', 'AM', NULL, NULL),
(391, 'The Animals', 'jenma@vante.com', 'S', 'AO', NULL, NULL),
(392, 'The B-52', 'ajepiiho@puwog.io', 'S', 'AQ', NULL, NULL),
(393, 'The Babys', 'fovvogaf@uhnaj.io', 'S', 'AR', NULL, NULL),
(394, 'The Band', 'for@satobvah.io', 'S', 'AS', NULL, NULL),
(395, 'The Beach Boys', 'ki@fiba.com', 'S', 'AT', NULL, NULL),
(396, 'The Beatles', 'baw@igiwa.gov', 'S', 'AU', NULL, NULL),
(397, 'The Black Crowes', 'ziri@zob.org', 'S', 'AW', NULL, NULL),
(398, 'The Black Keys', 'uba@goevimo.gov', 'S', 'AZ', NULL, NULL),
(399, 'The Blues Brothers', 'ko@hur.org', 'S', 'BA', NULL, NULL),
(400, 'The Byrds', 'atdihboh@bi.io', 'S', 'BB', NULL, NULL),
(401, 'The Cars', 'baw@jecwo.io', 'S', 'BD', NULL, NULL),
(402, 'The Clash', 'lesnuefu@ughanuno.gov', 'S', 'BE', NULL, NULL),
(403, 'The Cult', 'fozil@egsun.com', 'S', 'BF', NULL, NULL),
(404, 'The Doobie Brothers', 'siave@paclenor.gov', 'S', 'BG', NULL, NULL),
(405, 'The Doors', 'fokuheapa@saphaob.gov', 'S', 'BH', NULL, NULL),
(406, 'The Fabulous Thunderbirds', 'oc@ekece.edu', 'S', 'BI', NULL, NULL),
(407, 'The Firm', 'giw@niwowe.co.uk', 'S', 'BJ', NULL, NULL),
(408, 'The Fixx', 'le@ho.edu', 'S', 'BM', NULL, NULL),
(409, 'The Goo Goo Dolls', 'vugoheaw@wijibbeb.co.uk', 'S', 'BN', NULL, NULL),
(410, 'The James Gang', 'wendul@gunca.gov', 'S', 'BO', NULL, NULL),
(411, 'The Kings', 'bu@cit.net', 'S', 'BQ', NULL, NULL),
(412, 'The Kinks', 'timir@apobaas.io', 'S', 'BR', NULL, NULL),
(413, 'The Knack', 'noh@siodbim.io', 'S', 'BS', NULL, NULL),
(414, 'The Lemonheads', 'maf@nej.com', 'S', 'BT', NULL, NULL),
(415, 'The Lovin Spoonful', 'pa@agifoim.net', 'S', 'BV', NULL, NULL),
(416, 'The Mamas ', 'pam@sag.net', 'S', 'BW', NULL, NULL),
(417, 'The Marshall Tucker Band', 'waokaf@li.net', 'S', 'BY', NULL, NULL),
(418, 'The Moody Blues', 'goginga@oli.edu', 'T', 'BZ', NULL, NULL),
(419, 'The New Eagles', 'boz@viseas.co.uk', 'T', 'CA', NULL, NULL),
(420, 'The Offspring', 'beji@lijzozjid.org', 'T', 'CD', NULL, NULL),
(421, 'The Outfield', 'didma@une.gov', 'T', 'CH', NULL, NULL),
(422, 'The Outlaws', 'um@funowfak.co.uk', 'T', 'CI', NULL, NULL),
(423, 'The Police', 'ewcad@punbiwwug.com', 'T', 'CK', NULL, NULL),
(424, 'The Power Station', 'fev@om.co.uk', 'T', 'CL', NULL, NULL),
(425, 'The Pretenders', 'cikiliz@vacdel.com', 'T', 'CM', NULL, NULL),
(426, 'The Ramones', 'je@lesulof.io', 'T', 'CN', NULL, NULL),
(427, 'The Romantics', 'fawag@atonito.com', 'T', 'CO', NULL, NULL),
(428, 'The Small Faces', 'ratjis@rohrokwa.com', 'T', 'CR', NULL, NULL),
(429, 'The Smithereens', 'taltok@vi.org', 'T', 'CU', NULL, NULL),
(430, 'The Spencer Davis Group', 'ku@vivgoru.com', 'T', 'CV', NULL, NULL),
(431, 'The Standells', 'bekuzba@inaabmav.org', 'T', 'AM', NULL, NULL),
(432, 'The Traveling Wilburys', 'ran@wolla.edu', 'S', 'AO', NULL, NULL),
(433, 'The Tubes', 'siaciud@emwodlak.org', 'S', 'AQ', NULL, NULL),
(434, 'The Wallflowers', 'jazokza@jovoc.co.uk', 'S', 'AR', NULL, NULL),
(435, 'The White Stripes', 'kud@itgibe.gov', 'S', 'AS', NULL, NULL),
(436, 'The Who', 'dasal@su.io', 'S', 'AT', NULL, NULL),
(437, 'The Youngbloods', 'bi@idival.co.uk', 'S', 'AU', NULL, NULL),
(438, 'Thin Lizzy', 'esu@wiv.io', 'S', 'AW', NULL, NULL),
(439, 'Third Eye Blind', 'ad@la.org', 'S', 'AZ', NULL, NULL),
(440, 'Thunderclap Newman', 'iji@ugak.org', 'S', 'BA', NULL, NULL),
(441, 'Todd Rundgren', 'ginigzu@pahi.io', 'S', 'BB', NULL, NULL),
(442, 'Tom Cochrane', 'iwajeiru@ab.com', 'S', 'BD', NULL, NULL),
(443, 'Tom Petty & The Heartbreakers', 'godju@pe.io', 'S', 'BE', NULL, NULL),
(444, 'Tommy Tutone', 'gujgol@ababivno.io', 'S', 'BF', NULL, NULL),
(445, 'Tonic', 'ripihe@saro.gov', 'S', 'BG', NULL, NULL),
(446, 'Toto', 'iv@porzuwac.io', 'S', 'BH', NULL, NULL),
(447, 'Traffic', 'jahwafvo@heafsu.edu', 'S', 'BI', NULL, NULL),
(448, 'Trapeze', 'nesser@melil.co.uk', 'S', 'BJ', NULL, NULL),
(449, 'Triumph', 'zif@mowud.gov', 'S', 'BM', NULL, NULL),
(450, 'Turtles', 'gazalhul@dumikgef.net', 'S', 'BN', NULL, NULL),
(451, 'Twisted Sister', 'vi@siltaj.edu', 'S', 'BO', NULL, NULL),
(452, 'U2', 'ohelu@rofeoha.edu', 'S', 'BQ', NULL, NULL),
(453, 'UB40', 'fa@kofol.com', 'S', 'BR', NULL, NULL),
(454, 'UFO', 'temu@ewuri.co.uk', 'S', 'BS', NULL, NULL),
(455, 'Uriah Heep', 'fiv@erebawud.edu', 'S', 'BT', NULL, NULL),
(456, 'Van Halen', 'jul@ovuokituz.org', 'S', 'BV', NULL, NULL),
(457, 'Van Morrison', 'ah@adojovapu.edu', 'S', 'BW', NULL, NULL),
(458, 'Violent Femmes', 'bopnegol@jicoja.org', 'S', 'BY', NULL, NULL),
(459, 'Vixen', 'foser@pihiwpa.io', 'St', 'BZ', NULL, NULL),
(460, 'War', 'idta@kij.com', 'St', 'CA', NULL, NULL),
(461, 'Warrant', 'umwam@vibos.net', 'St', 'CD', NULL, NULL),
(462, 'Warren Zevon', 'gir@sabumnaw.gov', 'St', 'CH', NULL, NULL),
(463, 'Weezer', 'mano@cumnawoh.org', 'St', 'CI', NULL, NULL),
(464, 'Wet Willie', 'ilcerere@fan.net', 'St', 'CK', NULL, NULL),
(465, 'White Lion', 'tuded@bejda.com', 'St', 'CL', NULL, NULL),
(466, 'Whitesnake', 'ka@muc.gov', 'St', 'CM', NULL, NULL),
(467, 'Why Not', 'me@izkomvi.org', 'St', 'CN', NULL, NULL),
(468, 'Wild Cherry', 'hozzupez@eccif.gov', 'St', 'CO', NULL, NULL),
(469, 'Wildlife', 'vuj@giprazel.io', 'St', 'CR', NULL, NULL),
(470, 'Winger', 'vet@uwcurem.co.uk', 'T', 'CR', NULL, NULL),
(471, 'Wishbone Ash', 'pog@ejidiev.net', 'T', 'CR', NULL, NULL),
(472, 'Y&T', 'cefzul@namo.io', 'T', 'CR', NULL, NULL),
(473, 'Yes', 'pe@sovdahu.io', 'T', 'CR', NULL, NULL),
(474, 'Zebra', 'vov@jub.org', 'T', 'CR', NULL, NULL),
(475, 'Zombies', 'dusopcez@zac.io', 'T', 'CR', NULL, NULL),
(476, 'ZZ Top', 'dohajso@gatez.com', 'T', 'CR', NULL, NULL);
SET FOREIGN_KEY_CHECKS = 1;