INSERT INTO `venue` (`VenueId`, `Name`, `LocationId`) VALUES
('H1', 'Dreifaltigkeitssäule', 1),
('H2', 'Mader Reisen', 1),
('H3', 'Haltestelle', 1),
('H4', 'Altes Rathaus', 1),
('H5', 'Fa. Mammut', 1),
('H6', 'Bank Austria', 1),
('P1', 'Keplersalon', 2),
('P2', 'Adalbert-Stifter-Platz', 2),
('P3', 'Stadtpfarrkirche', 2),
('P4', 'Pfarrgasse 3', 2),
('P5', 'Pfarrplatz', 2),
('P6', 'Domgasse / Postamt', 2),
('Z	', 'Spektakelzelt', 2),
('A1', 'Klosterstrasse 7', 3),
('A2', 'Landhaus', 3),
('A3', 'Altstadt 13', 3),
('A4', 'Alter Markt', 3),
('A5', 'Hofgasse 13', 3),
('A6', 'Schlossmuseum', 3),
('L1', 'Annagasse', 4),
('L2', 'Taubenmarkt / Radio OÖ Bühne', 4),
('L3', 'Bethlehemstraße', 4),
('L4', 'Spittelwiese 4', 4),
('L5', 'Ursulinenkirche', 4),
('L6', 'Karmeliterkirche', 4),
('L7', 'OK-Platz', 4),
('L8', 'Martin-Luther-Platz', 4),
('X1', 'Café Traxlmayr', 5),
('X2', 'Sparkasse OÖ', 5),
('X3', 'Promenade 17', 5),
('X4', 'Medienhaus Wimmer', 5),
('T1', 'Altes Rathaus', 6),
('T2', 'Tummelplatz', 6),
('T3', 'Landhaus Arkadenhof', 6),
('T4', 'Landhaus', 6),
('T5', 'Sparkassenplatz', 6),
('T6', 'Domplatz', 6);